spring.application.name=reservation

# Database Configuration (Supabase Direct URL)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.pcynvlaufxlwstnxaebg
spring.datasource.password=Templerun@4242
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=SpringBootHikariCP

# JPA/Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Redis Configuration (Upstash TLS/SSL)
spring.data.redis.host=fun-dogfish-94166.upstash.io
spring.data.redis.port=6379
spring.data.redis.ssl.enabled=true
spring.data.redis.password=gQAAAAAAAW_WAAIgcDJiM2YxMTVmOTk0MzY0M2Q0YThkZDExODIxNWM2M2JjMQ

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl